FROM python:3.11-slim

# Install curl, git and docker
RUN apt-get update && apt-get install -y \
  curl \
  git \
  docker.io \
  && rm -rf /var/lib/apt/lists/*

# Install node
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
  && apt-get install -y nodejs

# Install poetry
RUN pip install poetry

WORKDIR /workspace
