pipeline {
  agent {
    docker {
      image 'myorg/ci-runner:latest'
      args '-u root:root -v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

  stages {
    stage('checkout') {
      steps {
        checkout scm
      }
    }

    stage('install dependencies') {
      steps {
        sh '''
            cd services
            pip install poetry
            poetry config virtualenvs.create false
            poetry install --no-interaction --no-root || false
        '''
      }
    }

    stage('Run backend tests') {
      steps {
        sh '''
          cd services
          poetry run pytest || true
        '''
      }
    }

    stage('Build Backend - api_gateway') {
      steps {
        sh '''
          docker build -t mealapp-api-gateway ./services/api_gateway
        '''
      }
    }

    stage('Build Backend - orders') {
      steps {
        sh '''
          docker build -t mealapp-orders ./services/orders
        '''
      }
    }

    stage('Build Frontend') {
      steps {
        sh '''
          docker build -t mealapp-frontend ./services/frontend
        '''
      }
    }

  }

  post {
    always {
      echo "Pipeline finished!"
    }
  }
}